---
title: "PSTAT 194 Individual Final Messing Around"
author: "Ayden Kelleher"
date: "2026-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages('igraph')
library(igraph)

edges_matrix <- as.matrix(read.csv("C:\\Users\\tayde\\OneDrive\\Documents\\PSTAT 194\\musae_squirrel_edges.csv"))

edges_matrix[,1] <- factor(edges_matrix[,1]) # if we dont change this to factor, then there are too many id names idk. If you don't believe me comment this out :/

g <- graph_from_edgelist(edges_matrix, directed = FALSE)

```

```{r}
length(V(g)) #this is exactly what the help page says
length(E(g)) #this is quite a few more edges than the help page says
```


```{r}
set.seed(30426)
sub.network1 <- induced_subgraph(g, sample(V(g), 200))

plot(sub.network1,
  vertex.size=10,
  vertex.label.cex=.4,
  edge.width=2)
```
```{r}
between1 <- betweenness(sub.network1)
plot(
  sub.network1,
  vertex.size= 2*log(between1+1),
  vertex.label.cex=.4,
  edge.width=2
  )

degree1 <- degree(sub.network1)
plot(
  sub.network1,
  vertex.size= (degree1)^(1/3)+5,
  vertex.label.cex=.4,
  edge.width=2
  )
```

```{r}
set.seed(10426)
sub.network2 <- induced_subgraph(g, sample(V(g), 200))

plot(sub.network2,
  vertex.size=10,
  vertex.label.cex=.4,
  edge.width=2)
```


```{r}
set.seed(10526)
sub.network3 <- induced_subgraph(g, sample(V(g), 200))

plot(sub.network3,
  vertex.size=10,
  vertex.label.cex=.4,
  edge.width=2)
```

```{r}
set.seed(10626)
sub.network4 <- induced_subgraph(g, sample(V(g), 200))

plot(
  sub.network4,
  vertex.size=10,
  vertex.label.cex=.4,
  edge.width=2
)
```




